name: 'Verify Pull Request Labels'
author: 'Jesus Vasquez'
description: 'Verify that the PR has a valid label'
branding:
  icon: 'check'
  color: 'gray-dark'
inputs:
  github-token:
    description: 'The GitHub token'
    required: true
  pull-request-number:
    description: 'The Pull Request number'
    required: false
  regex:
    description: 'Regex to check labels'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.pull-request-number }}
    - ${{ inputs.regex }}